### ISSUE TITLE
Weird invite button problem

### ISSUE THREAD

**Issue by pjootr93** [Exslims/MercuryTrade#65] opened 2017-04-05 14:57 UTC
Sometimes when i click on invite button app sends name of item to buyer instead off inviting him to party.

**Comment by Exslims** [comment] 2017-04-05 17:26
really weird, i will try to find the cause.

**Comment by zbytt** [comment] 2017-04-07 21:25
Additionaly, when you have opened chat, insted of inviting someone to party,  just writes the name of buyer in local chat

**Comment by etofok** [comment] 2017-04-08 11:15
When you press a button, Mercury sends "enter - /command / enter" sequence. If you open chat or put something in-focus where you can type - IT WILL NOT WORK.

**Comment by zbytt** [comment] 2017-04-08 11:53
It's pretty clear for me, but can be confusing for new users

**Comment by zbytt** [comment] 2017-04-08 11:58
Maybe the solution for this is to display a warning when clicking "enter" when the popup with new trade is displayed ( and disable the invite btn for example ?)

**Comment by etofok** [comment] 2017-04-08 12:14
Mercury doesn't know about your chat focus state. You can press "enter" during a loading screen or when pricing items or whatever in other words it's not possible for us to track it in a legit way.

**Comment by zbytt** [comment] 2017-04-08 12:20
Maybe it should be documented somewhere (ofc the truth is that users won't read that anywhay)

**Comment by Exslims** [comment] 2017-04-09 16:05
in next version will be fixed.

**Closed as completed** 2017-04-09 16:05 UTC
